name: Build LaTeX manuals and tutorials
on: [push]
jobs:
  build-lang-man:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: documentation/VDM10LangMan/VDM10_lang_man.tex
          work_in_root_file_dir: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: documentation/VDM10LangMan/VDM10_lang_man.pdf
